parameters:
  path: ''
  framework: ''

steps:
- template: parameter.yml
  parameters:
    name: path
    value: ${{ parameters.path }}
- template: parameter.yml
  parameters:
    name: framework
    value: ${{ parameters.framework }}
- task: DotNetCoreCLI@2
  displayName: ${{ format('dotnet build -f {0}', parameters.framework) }}
  inputs:
    command: build
    projects: ${{ parameters.path }}
    arguments: ${{ format('-f {0} -c Release', parameters.framework) }}
