parameters:
  name: ''  # defaults for any parameters that aren't specified
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    name: ${{ parameters.vmImage }}
  steps:
    - template: install.yml
    - template: tests.yml
